# Generated by Django 5.0.3 on 2024-03-16 20:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_apps', '0004_plan_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('user', 'name')},
        ),
    ]
